// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// AUTO-GENERATED by tools/gen_difftest.js — do not edit by hand.
// Expected hashes come from the JS reference renderer over FX-001..FX-030.

import {Test} from "forge-std/Test.sol";
import {RenderStateV1} from "../src/RenderState.sol";
import {HOODRXCHRenderer} from "../src/HOODRXCHRenderer.sol";

contract Differential is Test {
    HOODRXCHRenderer internal r;

    function setUp() public {
        r = new HOODRXCHRenderer();
    }

    function defaultState(uint256 tokenId) internal pure returns (RenderStateV1 memory s) {
        s.schemaVersion = 1;
        s.tokenId = tokenId;
        s.artIndex = tokenId;
        s.wardId = ((tokenId - 1) % 3) + 1;
        s.blockId = (((tokenId - 1) / 3) % 6) + 1;
        s.genesisHash = keccak256(abi.encodePacked("HOODRXCH_GENESIS_V1", tokenId));
        s.warId = 1;
        s.campaignId = 1;
        s.seasonId = 1;
        s.activeBlockId = 1;
        s.exposureState = 1;
        s.sealsRemaining = 3;
        s.historicalStateCount = 1;
    }

    function state_FX_001() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(1);
    }

    function test_FX_001() public view {
        RenderStateV1 memory s = state_FX_001();
        assertEq(r.stateHash(s), bytes32(0x141ec7fdb59cdc558c1da9978131e0165a618e8bf668217d2a625497e6802ff8), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x9d8ac8b7a903e6fd2a8df8ce3c7e8ce0baf9da2b16cbdddbd30f157955e7e376), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xc89eb766ef254b3db0fb0fc24a1e8184868dbdbcf4ab4de5dbb241a583d540eb), "metadata");
        assertEq(keccak256(bytes(r.renderBanner(s))), bytes32(0x55c45252da4653e702e6b97ab2e0faa0700be11b554c8ff6e8d9bcb222c95f57), "banner");
    }

    function state_FX_002() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(2);
        s.kills = 1;
    }

    function test_FX_002() public view {
        RenderStateV1 memory s = state_FX_002();
        assertEq(r.stateHash(s), bytes32(0xb292e2acb1c235033c0152a5614682ee58bea796891bc23562b2add67cc7cdf2), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x91dd83a35cd17d3514d176607f97001e3da8e70f5f317a7f0602b3c9ad024ab3), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x98aebb9e91f9067fa35569f73585d12af293e50a6da36f4f0743dc020228e8e8), "metadata");
    }

    function state_FX_003() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(3);
        s.kills = 10;
    }

    function test_FX_003() public view {
        RenderStateV1 memory s = state_FX_003();
        assertEq(r.stateHash(s), bytes32(0xfdc780ec885625315215544ae80820e7097536a1d9cc2f9e33a2cf2c43e2c629), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xfb3f882b078c195a28f730cf2da27702c5abef74d8a1dc7a823deadea05dcec4), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xc545a776cace48d4cda2ccaa8255ca5208689a2d05a99bcf8721358ec59d00fa), "metadata");
    }

    function state_FX_004() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(4);
        s.kills = 25;
    }

    function test_FX_004() public view {
        RenderStateV1 memory s = state_FX_004();
        assertEq(r.stateHash(s), bytes32(0x6e1db89f3353d389cdb6d85e7d79f293253ff5c5c757525421826bc6653c59b2), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x1f60412861051886b2407b9ab1d68e4508dccf673cd2616fe4e7afffcb980b06), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x353151f26aa27b5cb62b54c271bf9d375b47e49c4d0d4f80013255f9f34d53a9), "metadata");
    }

    function state_FX_005() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(5);
        s.kills = 50;
    }

    function test_FX_005() public view {
        RenderStateV1 memory s = state_FX_005();
        assertEq(r.stateHash(s), bytes32(0x453057e407858f1862ddce338e811a2632b3680360a0a574826957aad43a1b0b), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xe154a4c45215cb7e8bda12178649f21b60e0b2238b91fbc66d1bfeaee4916992), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xe3726ed1107181dc62eb40cf383aa77983a4cff6c8abc74275662654661e62b0), "metadata");
    }

    function state_FX_006() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(6);
        s.kills = 75;
    }

    function test_FX_006() public view {
        RenderStateV1 memory s = state_FX_006();
        assertEq(r.stateHash(s), bytes32(0x656beb81a78eb2575a50a06776953a4259678712e0c7f0258a7e09c07a1260e9), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xfc6748c6189370ed1dc3b6574c9a4a25100d450fe06e1226300199e38068dd34), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xb1ec5522ed00d5959bd1846f59f280d7bf927628e131b034fb0e782bd5ed11c4), "metadata");
    }

    function state_FX_007() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(7);
        s.kills = 100;
    }

    function test_FX_007() public view {
        RenderStateV1 memory s = state_FX_007();
        assertEq(r.stateHash(s), bytes32(0x9cb84a9ebe63057473412f190a745bdab1e887e7d0bdd0e9f6f2a9510ac9437b), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x3c13ac10e3a69bb9753f2701ce191f5af9dc688e11a291c4c34ae8f3f9c585f0), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xee7b5a71610ab438cd872db28923638fae16e3092a8d91b5cd07590cde2f3efc), "metadata");
        assertEq(keccak256(bytes(r.renderBanner(s))), bytes32(0x3db1f4658bfb95b85f1c99a9b5f10c28b9340c7de44169c05c37e95c0c96e569), "banner");
    }

    function state_FX_008() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(8);
        s.hunterSelected = true;
    }

    function test_FX_008() public view {
        RenderStateV1 memory s = state_FX_008();
        assertEq(r.stateHash(s), bytes32(0x65f7c49ac4c585b6ed4e9c3e394f0aafcef4921f0d61133b50c2999bb73eac11), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x1def2155fe49a627622171a07271b2ce8c9070210d09b2e6125441e89eee1dee), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x9e8af47b0884022e8a309532aa518215fec561684eff825246957f50e66ae9c1), "metadata");
    }

    function state_FX_009() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(9);
        s.lifeState = 1;
        s.marked = true;
        s.markedByTokenId = 66;
        s.purgeDeadline = 1790000000;
    }

    function test_FX_009() public view {
        RenderStateV1 memory s = state_FX_009();
        assertEq(r.stateHash(s), bytes32(0x28c76e634f013fac2ce1a51f08e73c8ccea2113256400575512af12117be37a6), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xa97f2a7b2ee7f205b0d3428a1a799c5c79028228cc97484ddb5374f22963746b), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xcd3c168b2872958ecae6818e29aa127c116b906b6c72f318fd96c93fbc287ed5), "metadata");
        assertEq(keccak256(bytes(r.renderBanner(s))), bytes32(0x6d4d8eea57d9c3b4dc4b6af7728397c375dc5f590df95be9989f90700cfd42b6), "banner");
    }

    function state_FX_010() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(10);
        s.lifeState = 1;
        s.marked = true;
        s.markedByTokenId = 13;
        s.purgeDeadline = 1790000000;
        s.kills = 100;
    }

    function test_FX_010() public view {
        RenderStateV1 memory s = state_FX_010();
        assertEq(r.stateHash(s), bytes32(0x2f0b6ba156c0795c504fc47686ac3c52c251bc6f67a7a90fff44ecb6d7ec8b91), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xb1a4e8cbeeaef9b6aabfa814bff52491b488d520e2d70ecee9aa86112025fbd6), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x859228daba22c764b3c9bdf99500c5a661c0c2d1eb77c9b1a6159bb5969f0522), "metadata");
    }

    function state_FX_011() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(11);
        s.witsecApplies = true;
        s.exposureState = 3;
    }

    function test_FX_011() public view {
        RenderStateV1 memory s = state_FX_011();
        assertEq(r.stateHash(s), bytes32(0xfeb121efc58df655e451d085f80bef3691984301f0defac9b74074fd0b0ac0de), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x1e1c88f14ec815a47291be30fd816acf6951bc082dbb1d66982df971a7dbbb96), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x425d24077f9a82726de70960bef24caf0cead9499aabde66b549ae67c93c1ff4), "metadata");
    }

    function state_FX_012() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(12);
        s.laidLow = true;
        s.exposureState = 2;
    }

    function test_FX_012() public view {
        RenderStateV1 memory s = state_FX_012();
        assertEq(r.stateHash(s), bytes32(0xdd6f5502106697553337bff7c998e9003d13fbf6279d9a2562d55c693b8e4c29), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xdb00fe1c145c1522f914fde2e6c55da8a3fcde40463d70d68b90f60d149c84f4), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x91f43fe98112ac1e1b54d310f9171cacf973b8fca9e3f197f54c8a86ad17698a), "metadata");
    }

    function state_FX_013() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(13);
        s.buyerProtected = true;
        s.exposureState = 4;
    }

    function test_FX_013() public view {
        RenderStateV1 memory s = state_FX_013();
        assertEq(r.stateHash(s), bytes32(0xf2a095f99e8465ee92e7e9ab1d74ec9393002cf63e8c3c8c8d2cbd9d69045e8e), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x77e4c8970df559b2a3972af6c05b21aaa2009d3851784bd12f0e4e313a61525a), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x3f82b58d2afae1008951af028908004beda2765b79a881491b673c1e5eb1d404), "metadata");
    }

    function state_FX_014() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(14);
        s.lifeState = 2;
        s.exposureState = 5;
        s.deaths = 1;
        s.sealsRemaining = 2;
    }

    function test_FX_014() public view {
        RenderStateV1 memory s = state_FX_014();
        assertEq(r.stateHash(s), bytes32(0x44073c3125f25161fc37eaa6dbd9c33d4540ed1269fddcfadbcd3fff6059f03d), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x6c29f0ddc0e9ce608e88d4e07dfa70c879e14e155915419271e6db74261c5039), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x85b67891ac26ff4951ae5f025cc1b3ac8f23ca94c2fca4aecb27d3e5494dd96a), "metadata");
    }

    function state_FX_015() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(15);
        s.lifeState = 2;
        s.exposureState = 5;
        s.deaths = 2;
        s.sealsRemaining = 1;
        s.kills = 25;
    }

    function test_FX_015() public view {
        RenderStateV1 memory s = state_FX_015();
        assertEq(r.stateHash(s), bytes32(0x7d3aca142c8be9db57f2c280ebc69a04db765e549a892ca4f3274038bb822b1c), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x529822714982a70a91ec8d4d26fdc112943792bef7f71e9f1dc8ed608a720085), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xa519d1de48f1c31e6bb6576dc93e0f14598c80b2648bef1c338fbbe415fa20be), "metadata");
    }

    function state_FX_016() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(16);
        s.lifeState = 3;
        s.exposureState = 6;
        s.deaths = 3;
        s.sealsRemaining = 0;
    }

    function test_FX_016() public view {
        RenderStateV1 memory s = state_FX_016();
        assertEq(r.stateHash(s), bytes32(0xf0639fc9539a542376f4087be152db9d8206bc9b17ecfa1fd955ff8e54b06018), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xa2ad0498081e5055596e4bc39b0c9b65b5ad8fd874c56e14a34bbd28e2be0377), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xb66f0fe9198be18f0bc0c19cc347aee489977682e25d68dec96845e4e24397b6), "metadata");
        assertEq(keccak256(bytes(r.renderBanner(s))), bytes32(0xcc5dcb31860a7df7dfef86032c105d3624ae50e23bbfa906a357678504dfab31), "banner");
    }

    function state_FX_017() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(17);
        s.lifeState = 3;
        s.exposureState = 6;
        s.deaths = 3;
        s.sealsRemaining = 0;
        s.kills = 100;
    }

    function test_FX_017() public view {
        RenderStateV1 memory s = state_FX_017();
        assertEq(r.stateHash(s), bytes32(0x1d6de56f903be4feb24e68f1d8fea383ee0fda3cad29146d15de29cacd11f1e6), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xacf6152a29d588510911e1c83e632b5908b168c0a58c80f9e22c4ab766e6d983), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x82d9a5bd35f31c2473f0167b9d2d78f00efb12a9a748e3f0ed326eb04126de04), "metadata");
    }

    function state_FX_018() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(18);
        s.deaths = 2;
        s.sealsRemaining = 1;
        s.kills = 30;
    }

    function test_FX_018() public view {
        RenderStateV1 memory s = state_FX_018();
        assertEq(r.stateHash(s), bytes32(0x707ca14d83b3383e7fc25170767bf18f22f8b5eab62183efbdc99c6137512f56), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x66ac5d7bba2026594e8510ad4d7c1e0f27f3d08ac53d6e59c8add3c6be9cb3aa), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x367bef3ede4997166ad3947bb18ece88120b0c35316b1a762f571bc660c11e9e), "metadata");
    }

    function state_FX_019() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(19);
        s.savesReceived = 5;
        s.savesGiven = 3;
    }

    function test_FX_019() public view {
        RenderStateV1 memory s = state_FX_019();
        assertEq(r.stateHash(s), bytes32(0xcc8a2ca987e5fb423f94008d4df780cda2f2920ca7bc4d4d465ab1870fd7991e), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x435b65c3c4620824a8d2e424d573b5c143e7c1dfc0d7d1f9d143e20e007c45be), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x5e97c1d9a40a04591743de10f222faded608d2602e1ef3a6af4beca1b5c2b8da), "metadata");
    }

    function state_FX_020() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(20);
        s.forcedPurges = 10;
    }

    function test_FX_020() public view {
        RenderStateV1 memory s = state_FX_020();
        assertEq(r.stateHash(s), bytes32(0xdbf5d48ae1e57bf243f931ed65ea2a05cfe3f097b92fce7b5886c2f439107102), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xf316f792e54f5b362a2a9934a07b8c281629eca2d1a81cafb66faba0d7e5d485), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xc53ce129307c49135eca63498467f3960914030110c9da410e024511beff2fa5), "metadata");
    }

    function state_FX_021() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(21);
        s.currentKillStreak = 7;
        s.kills = 12;
    }

    function test_FX_021() public view {
        RenderStateV1 memory s = state_FX_021();
        assertEq(r.stateHash(s), bytes32(0xc1d41de71f7fed5f574f2780060055f104f591166b3bc2a16f0867243b4916c7), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x0646840550b893bf169b75ba341b62bf3348d2f53cd0075a0c41bae73144488c), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xb008427eddeed80b643843cba7cac301851d621834de67e61f4635a7b129b892), "metadata");
    }

    function state_FX_022() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(22);
        s.latestSeasonBadgeFlags = 1;
        s.latestSeasonRank = 7;
        s.latestAwardSeasonId = 1;
    }

    function test_FX_022() public view {
        RenderStateV1 memory s = state_FX_022();
        assertEq(r.stateHash(s), bytes32(0xe96413dccc5910a02a53f7b7880b93915be44fc2cc1713b2a13bc6aeb3feb042), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x25150283d6f5d440396864587ee2bf6edceda58532212d6cb0278b58aa072ea0), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xc9c24f244d2a39a25bd382f4b05dbc62bf0af6b1ce45d130da78beeaf202defd), "metadata");
    }

    function state_FX_023() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(23);
        s.latestSeasonBadgeFlags = 3;
        s.latestSeasonRank = 2;
        s.latestAwardSeasonId = 2;
    }

    function test_FX_023() public view {
        RenderStateV1 memory s = state_FX_023();
        assertEq(r.stateHash(s), bytes32(0xf890f9e762779b9b9d1dc9f2d149bee6cc90ab96993a3d31d29b9aeea39ac7ba), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x36ef8568aa0b81384476422b148ecb6050ef911d02fec4838ea5f1a0d99a2d48), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xee0175311ccf0d137c394d903f437c32d91f2df93588756f243e88c78b979da7), "metadata");
    }

    function state_FX_024() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(24);
        s.territoryAchievementCount = 6;
        s.kills = 50;
    }

    function test_FX_024() public view {
        RenderStateV1 memory s = state_FX_024();
        assertEq(r.stateHash(s), bytes32(0x47ee6f3bbc4e64645de6628803f31576a48b4ad907d6e6b374c0b7773ab65901), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xee3fffde55b9b7da25b9bc9976f05e4e1bd3bbd3e7bb6d81cd01efbadaf4f2e5), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x09daab99f1bfe8d92095eeb1b2abaa1e233db6db09f7c4509592378f1aac0b03), "metadata");
    }

    function state_FX_025() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(25);
        s.displayMode = 1;
        s.kills = 25;
        s.deaths = 1;
        s.sealsRemaining = 2;
        s.currentKillStreak = 3;
    }

    function test_FX_025() public view {
        RenderStateV1 memory s = state_FX_025();
        assertEq(r.stateHash(s), bytes32(0x23cd012c6fcea9b9cc4159fbadfaf5115ce5276a536618b8d084e88dfeb1f69b), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x2c4a16ee66fdaac20c3bc75d2052b6cc47957f9abc66d3be6cb9ddcefb1c4064), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x584c84694682663b008badb5e2fe3e3ee415bc240914712b5a4d5d08546c4b96), "metadata");
    }

    function state_FX_026() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(26);
        s.flicker = true;
        s.kills = 10;
    }

    function test_FX_026() public view {
        RenderStateV1 memory s = state_FX_026();
        assertEq(r.stateHash(s), bytes32(0xeb99c068fe4c3b4b8736cce3dfa39c183cebe0915dc58a71e0e2836e446c0954), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xd1deac6426cc535307e05813d29480628eae02412ccf3c2dfa0bca4c72e65b5d), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x7da5a113302fb62cbf01e3ca8e1ffab0deace01ec62711b68f4fa497d7e0eee7), "metadata");
    }

    function state_FX_027() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(27);
        s.kills = 75;
        s.deaths = 1;
        s.sealsRemaining = 2;
        s.forcedPurges = 6;
        s.savesReceived = 3;
        s.latestSeasonBadgeFlags = 3;
        s.latestSeasonRank = 1;
        s.latestAwardSeasonId = 1;
        s.territoryAchievementCount = 4;
        s.currentKillStreak = 5;
    }

    function test_FX_027() public view {
        RenderStateV1 memory s = state_FX_027();
        assertEq(r.stateHash(s), bytes32(0x94a38a1be0c640af2ba0fb7f13c73975919a27de606875dc2a9c98d32320291a), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xd67b470dfd24c36397f1e649e003f850895bd4f56a7c841072905c6d6c4fc6b8), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x4539205ee671cdb25862cbf26ea3792f2798cb2006402a6ca3ba9106c1efe441), "metadata");
    }

    function state_FX_028() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(28);
        s.sealsRemaining = 0;
    }

    function test_FX_028() public view {
        RenderStateV1 memory s = state_FX_028();
        assertEq(r.stateHash(s), bytes32(0xda4ef24e43b1f47d1fb4b57c1287b70cb30e0f8f309da25150d2f16d6b76dcc1), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x4e1020874634d4fed2929e675fd961f3d5bd539a72eb3a815692886bf4924940), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x78593def040fec7d811019c580a048d135773dee14a24718d33c6e40541ebe20), "metadata");
        assertEq(keccak256(bytes(r.renderBanner(s))), bytes32(0x16f973f6682d71afa753344d1f431db29084b683a380fc6d257ddd53ae1a563c), "banner");
    }

    function state_FX_029() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(29);
        s.witsecApplies = true;
        s.laidLow = true;
        s.exposureState = 3;
    }

    function test_FX_029() public view {
        RenderStateV1 memory s = state_FX_029();
        assertEq(r.stateHash(s), bytes32(0x14b859a6643a70d1ccebd3457bdb30e11c8f5ca24897d556a2cd13ae38cf513a), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x0e7099cccfbf66e0bc8bb4bac0ab1d5918ba5fe9ae316a91d6757b62cb57fa50), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x1e24bf0c5a03ad897df1236b00f4ab05f89bc33c836029a5e0cda3ede04fd243), "metadata");
    }

    function state_FX_030() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(30);
        s.lifeState = 3;
        s.exposureState = 6;
        s.deaths = 3;
        s.sealsRemaining = 0;
        s.marked = true;
    }

    function test_FX_030() public view {
        RenderStateV1 memory s = state_FX_030();
        assertEq(r.stateHash(s), bytes32(0x8dd94935c083ceff847ef5697cb033c237695edce16f75e4ab22c1dee478d082), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xb0755756cfb191df7c843f35773a73df980291665da10ef60ec26f1f1bf6db38), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xb1fd19cb85233fa22feeba2febfe134a14b6af460f3cbb516dbcdf3bb6b3f8dd), "metadata");
    }

}
