// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// AUTO-GENERATED by tools/gen_difftest.js — do not edit by hand.
// Expected hashes come from the JS reference renderer over FX-001..FX-030.

import {Test} from "forge-std/Test.sol";
import {RenderStateV1} from "../src/RenderState.sol";
import {HOODRXCHRenderer} from "../src/HOODRXCHRenderer.sol";

contract Differential is Test {
    HOODRXCHRenderer internal r;

    function setUp() public {
        r = new HOODRXCHRenderer();
    }

    function defaultState(uint256 tokenId) internal pure returns (RenderStateV1 memory s) {
        s.schemaVersion = 1;
        s.tokenId = tokenId;
        s.artIndex = tokenId;
        s.wardId = ((tokenId - 1) % 3) + 1;
        s.blockId = (((tokenId - 1) / 3) % 6) + 1;
        s.genesisHash = keccak256(abi.encodePacked("HOODRXCH_GENESIS_V1", tokenId));
        s.warId = 1;
        s.campaignId = 1;
        s.seasonId = 1;
        s.activeBlockId = 1;
        s.exposureState = 1;
        s.sealsRemaining = 3;
        s.historicalStateCount = 1;
    }

    function state_FX_001() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(1);
    }

    function test_FX_001() public view {
        RenderStateV1 memory s = state_FX_001();
        assertEq(r.stateHash(s), bytes32(0x141ec7fdb59cdc558c1da9978131e0165a618e8bf668217d2a625497e6802ff8), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x7e88c29db195e5609640543d5d71a7efe9cd3c266a6312129a54958394a7d2be), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x6cd8a411a86cdb4ba559a9a3855c987d2aed2eaf23d5fe5000598b5d317ffad4), "metadata");
        assertEq(keccak256(bytes(r.renderBanner(s))), bytes32(0xbb306bd61ac87fc00be425b976f63196b5768fd67c4707397c9eb027582e6d75), "banner");
    }

    function state_FX_002() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(2);
        s.kills = 1;
    }

    function test_FX_002() public view {
        RenderStateV1 memory s = state_FX_002();
        assertEq(r.stateHash(s), bytes32(0xb292e2acb1c235033c0152a5614682ee58bea796891bc23562b2add67cc7cdf2), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x8bf2073b9a63577be29ddd118a83152209e98a92b02034926659fdfd70266882), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x675e89488f653ac4dd9d56055c62ea2ff8cf2f22e1e1c69d13ee95ba687f3d5e), "metadata");
    }

    function state_FX_003() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(3);
        s.kills = 10;
    }

    function test_FX_003() public view {
        RenderStateV1 memory s = state_FX_003();
        assertEq(r.stateHash(s), bytes32(0xfdc780ec885625315215544ae80820e7097536a1d9cc2f9e33a2cf2c43e2c629), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xf81418330d0f2036b4b15f903eb889dba10278625808800ca24198c4ce69d4ba), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xe4b6d76dd733caf24d0bc01d3b895fb95e8fc212d0ed2883a2c7970664d6f83b), "metadata");
    }

    function state_FX_004() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(4);
        s.kills = 25;
    }

    function test_FX_004() public view {
        RenderStateV1 memory s = state_FX_004();
        assertEq(r.stateHash(s), bytes32(0x6e1db89f3353d389cdb6d85e7d79f293253ff5c5c757525421826bc6653c59b2), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xe49c8bab413a59be3e1ccbf3752b1e88bbd81eb992b9470e02e836019fff98c6), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x9443464e96c9b990076bbc7ab18fc0c3f2fba283f0e3d2c09b1ed2f6483e6715), "metadata");
    }

    function state_FX_005() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(5);
        s.kills = 50;
    }

    function test_FX_005() public view {
        RenderStateV1 memory s = state_FX_005();
        assertEq(r.stateHash(s), bytes32(0x453057e407858f1862ddce338e811a2632b3680360a0a574826957aad43a1b0b), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xaaae9f76cc76dc62ecf3806fcc7df9ca741564dd03f4b47fac5d882573bd3404), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x69ba335c2a63f75b4e96ac137ce00e97a8e7e9265508517affa21744a2e9b280), "metadata");
    }

    function state_FX_006() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(6);
        s.kills = 75;
    }

    function test_FX_006() public view {
        RenderStateV1 memory s = state_FX_006();
        assertEq(r.stateHash(s), bytes32(0x656beb81a78eb2575a50a06776953a4259678712e0c7f0258a7e09c07a1260e9), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x46956a8be6b17e739474c472482e9bb1caaf527aff468d11d792851f80552e3c), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x3e6431fad476949f7e503c1692f1ecef4d0d5e1d8d2aab6cf0e6ae0552ee773f), "metadata");
    }

    function state_FX_007() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(7);
        s.kills = 100;
    }

    function test_FX_007() public view {
        RenderStateV1 memory s = state_FX_007();
        assertEq(r.stateHash(s), bytes32(0x9cb84a9ebe63057473412f190a745bdab1e887e7d0bdd0e9f6f2a9510ac9437b), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xc51c303cd0730a0296333cc39032c0a400ab085c3215c6c224f5804a7fc99bad), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xfb41055ed20ea31828c2a1bc8cb364fc4ed52f1d1fee76874c9ba9d9a1fad4c6), "metadata");
        assertEq(keccak256(bytes(r.renderBanner(s))), bytes32(0x5af508e9a8518afb0b0617d2aa432b83512a1bc810ebf4b2b4a04754688362af), "banner");
    }

    function state_FX_008() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(8);
        s.hunterSelected = true;
    }

    function test_FX_008() public view {
        RenderStateV1 memory s = state_FX_008();
        assertEq(r.stateHash(s), bytes32(0x65f7c49ac4c585b6ed4e9c3e394f0aafcef4921f0d61133b50c2999bb73eac11), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x8f02a6725ef490ac0313d5cc2cff946c3afd239c09804685ba803ef5c881c81d), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xd519e613b769123a85daaa1df4f2b80b1ca4644d5784792bcf6d6a652575085e), "metadata");
    }

    function state_FX_009() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(9);
        s.lifeState = 1;
        s.marked = true;
        s.markedByTokenId = 66;
        s.purgeDeadline = 1790000000;
    }

    function test_FX_009() public view {
        RenderStateV1 memory s = state_FX_009();
        assertEq(r.stateHash(s), bytes32(0x28c76e634f013fac2ce1a51f08e73c8ccea2113256400575512af12117be37a6), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x98f982c378a2c0305e79915e8a1be735fea4a903f01d522966a52a77569238ec), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xa3a55c0d1d5c793d8dd4ebd8bd15951cf02e980fe441990f8d532fa5a502d8af), "metadata");
        assertEq(keccak256(bytes(r.renderBanner(s))), bytes32(0x2801c9b171b98896ac7c976210cedc55f31f00334c708c0c1927cccb045a095c), "banner");
    }

    function state_FX_010() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(10);
        s.lifeState = 1;
        s.marked = true;
        s.markedByTokenId = 13;
        s.purgeDeadline = 1790000000;
        s.kills = 100;
    }

    function test_FX_010() public view {
        RenderStateV1 memory s = state_FX_010();
        assertEq(r.stateHash(s), bytes32(0x2f0b6ba156c0795c504fc47686ac3c52c251bc6f67a7a90fff44ecb6d7ec8b91), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x9ecebbeae0beae36a488ca4c338f2dddedfc9ce9e022cdd7c5f25f35604a59b2), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x6b6731201816bcea565d168aba3d0489006a8eee297e20f35160bbe303fab9ea), "metadata");
    }

    function state_FX_011() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(11);
        s.witsecApplies = true;
        s.exposureState = 3;
    }

    function test_FX_011() public view {
        RenderStateV1 memory s = state_FX_011();
        assertEq(r.stateHash(s), bytes32(0xfeb121efc58df655e451d085f80bef3691984301f0defac9b74074fd0b0ac0de), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xcb9f8124f33d6ef74dd280cea06ba90a6aab0f4817a4c602e11eb3c3cd743ec8), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x1cdcf71127646a43d0d87ffd0f8023d9840db20d006854e84046eb09fa3e4a41), "metadata");
    }

    function state_FX_012() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(12);
        s.laidLow = true;
        s.exposureState = 2;
    }

    function test_FX_012() public view {
        RenderStateV1 memory s = state_FX_012();
        assertEq(r.stateHash(s), bytes32(0xdd6f5502106697553337bff7c998e9003d13fbf6279d9a2562d55c693b8e4c29), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x0943a8e9c97fbad1d124c5754aa36c09f25275e44461709a525c8c188f79ef29), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x5d46a0330d59d0000e2c50d8ffb88bff596778f39a483d4bab6a7fe9ade70d74), "metadata");
    }

    function state_FX_013() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(13);
        s.buyerProtected = true;
        s.exposureState = 4;
    }

    function test_FX_013() public view {
        RenderStateV1 memory s = state_FX_013();
        assertEq(r.stateHash(s), bytes32(0xf2a095f99e8465ee92e7e9ab1d74ec9393002cf63e8c3c8c8d2cbd9d69045e8e), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x441ef2cbcadfa95d8519edce07fef1f38385534bfb6a15fd012ab3d03b4797aa), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xf0f99fa739acb8b84423da0026a5248fe6631e3145d8de951019472a6a5a29c6), "metadata");
    }

    function state_FX_014() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(14);
        s.lifeState = 2;
        s.exposureState = 5;
        s.deaths = 1;
        s.sealsRemaining = 2;
    }

    function test_FX_014() public view {
        RenderStateV1 memory s = state_FX_014();
        assertEq(r.stateHash(s), bytes32(0x44073c3125f25161fc37eaa6dbd9c33d4540ed1269fddcfadbcd3fff6059f03d), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x93e65bd46042c7aa84851df505e7c14d39ca325a2f5aef10c5c693dcda3e80cb), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x064561df00e37f1e8837bbba99ef884d73da0d23660822cf245af61c903b3f02), "metadata");
    }

    function state_FX_015() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(15);
        s.lifeState = 2;
        s.exposureState = 5;
        s.deaths = 2;
        s.sealsRemaining = 1;
        s.kills = 25;
    }

    function test_FX_015() public view {
        RenderStateV1 memory s = state_FX_015();
        assertEq(r.stateHash(s), bytes32(0x7d3aca142c8be9db57f2c280ebc69a04db765e549a892ca4f3274038bb822b1c), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x61c3e9e74e6671c365dd353f2849954c7bb806194e4dd443829b7ad58ee9ae9a), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x82aed49b4e6fa57090721cd71dac01f45d6062f52ada6c28d609111f9a2739d4), "metadata");
    }

    function state_FX_016() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(16);
        s.lifeState = 3;
        s.exposureState = 6;
        s.deaths = 3;
        s.sealsRemaining = 0;
    }

    function test_FX_016() public view {
        RenderStateV1 memory s = state_FX_016();
        assertEq(r.stateHash(s), bytes32(0xf0639fc9539a542376f4087be152db9d8206bc9b17ecfa1fd955ff8e54b06018), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xb7f7604ef50f6ecd1edccd2bebacb3dd32a86e8c0e1be4bfe778c623a58a3be3), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x5fd19d41dcc2150f85236ab0b4f91e4ae4228569fe23dca429fe40167ec50020), "metadata");
        assertEq(keccak256(bytes(r.renderBanner(s))), bytes32(0x5b641b8e2a13589ae8d8f5c4897d401ab635d79dcb6b7c22470c4743a0e0a3ad), "banner");
    }

    function state_FX_017() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(17);
        s.lifeState = 3;
        s.exposureState = 6;
        s.deaths = 3;
        s.sealsRemaining = 0;
        s.kills = 100;
    }

    function test_FX_017() public view {
        RenderStateV1 memory s = state_FX_017();
        assertEq(r.stateHash(s), bytes32(0x1d6de56f903be4feb24e68f1d8fea383ee0fda3cad29146d15de29cacd11f1e6), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x9639698f70309642430a5eac5a572dda14c1f72d7b2803c62c79be32677400c8), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x8cea6dbd783032409f2e55a8bb7713462c29c30777c838014ea219d3564e3c1b), "metadata");
    }

    function state_FX_018() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(18);
        s.deaths = 2;
        s.sealsRemaining = 1;
        s.kills = 30;
    }

    function test_FX_018() public view {
        RenderStateV1 memory s = state_FX_018();
        assertEq(r.stateHash(s), bytes32(0x707ca14d83b3383e7fc25170767bf18f22f8b5eab62183efbdc99c6137512f56), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xd23f31629900f45ee81161b8682a3d9d227a62e984fe1900f133780b0e68190d), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xfdd4e7b6a5a2675ae408698ccd5f543d9159606c9bdb64cd34f67c4e08f19f9b), "metadata");
    }

    function state_FX_019() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(19);
        s.savesReceived = 5;
        s.savesGiven = 3;
    }

    function test_FX_019() public view {
        RenderStateV1 memory s = state_FX_019();
        assertEq(r.stateHash(s), bytes32(0xcc8a2ca987e5fb423f94008d4df780cda2f2920ca7bc4d4d465ab1870fd7991e), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x3eb1a5731cbb20f0584903369949dbc0a3a2240ae5df6bfe8aa63fbe0aa32f3f), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x1faa972b66f1e61aeb247f3543316e67c1dbef802b3e926f96809dc8ba337766), "metadata");
    }

    function state_FX_020() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(20);
        s.forcedPurges = 10;
    }

    function test_FX_020() public view {
        RenderStateV1 memory s = state_FX_020();
        assertEq(r.stateHash(s), bytes32(0xdbf5d48ae1e57bf243f931ed65ea2a05cfe3f097b92fce7b5886c2f439107102), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x0d564d9851883c1e67c81fa68030972b5f0160f03a44bc12c1be263f3ecc2aaf), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x31f7ad446b3a29f3ecae132d926ed47529be2f7c9b5818775f414963c44c69e3), "metadata");
    }

    function state_FX_021() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(21);
        s.currentKillStreak = 7;
        s.kills = 12;
    }

    function test_FX_021() public view {
        RenderStateV1 memory s = state_FX_021();
        assertEq(r.stateHash(s), bytes32(0xc1d41de71f7fed5f574f2780060055f104f591166b3bc2a16f0867243b4916c7), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x1168c5dad044b96f8c82c3be78ef0dc57e822cf41333d037246474912911c821), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x2f9b59f47fc5aa3d352e75a38b6ff8e38e6b8bfa3bdfe8cd65bb4b72a9d320c1), "metadata");
    }

    function state_FX_022() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(22);
        s.latestSeasonBadgeFlags = 1;
        s.latestSeasonRank = 7;
        s.latestAwardSeasonId = 1;
    }

    function test_FX_022() public view {
        RenderStateV1 memory s = state_FX_022();
        assertEq(r.stateHash(s), bytes32(0xe96413dccc5910a02a53f7b7880b93915be44fc2cc1713b2a13bc6aeb3feb042), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xedecf18a394a464fdb62ac1f1ebf053e288b494b908219b5b1dfe76b9a703845), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x54dadfa6ee973306d31cb0d2b93c7c0fa30cb80bd6187c3f0ec05c8d1a629b34), "metadata");
    }

    function state_FX_023() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(23);
        s.latestSeasonBadgeFlags = 3;
        s.latestSeasonRank = 2;
        s.latestAwardSeasonId = 2;
    }

    function test_FX_023() public view {
        RenderStateV1 memory s = state_FX_023();
        assertEq(r.stateHash(s), bytes32(0xf890f9e762779b9b9d1dc9f2d149bee6cc90ab96993a3d31d29b9aeea39ac7ba), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xb6fff5a3478b7fa9f18a8465039c9da31303573653527d54587310e1ea27f28c), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xdb64c7d066e09ad5d71e0fb33fd9a49d001554700930a4e8b85b4074a404bf22), "metadata");
    }

    function state_FX_024() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(24);
        s.territoryAchievementCount = 6;
        s.kills = 50;
    }

    function test_FX_024() public view {
        RenderStateV1 memory s = state_FX_024();
        assertEq(r.stateHash(s), bytes32(0x47ee6f3bbc4e64645de6628803f31576a48b4ad907d6e6b374c0b7773ab65901), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xf8ec20a5851047c0e323a49f2b109f0ea343e707340a2eb3217218eeb70a2f38), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x706caa0d0b9585fa4e15d629bbc2b7726b7be337c598a0bbf0831ad708ccd947), "metadata");
    }

    function state_FX_025() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(25);
        s.displayMode = 1;
        s.kills = 25;
        s.deaths = 1;
        s.sealsRemaining = 2;
        s.currentKillStreak = 3;
    }

    function test_FX_025() public view {
        RenderStateV1 memory s = state_FX_025();
        assertEq(r.stateHash(s), bytes32(0x23cd012c6fcea9b9cc4159fbadfaf5115ce5276a536618b8d084e88dfeb1f69b), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x4b17a8181a77b532f447c702a377f5dcb60be750e2363e283bcd18be9d0916e9), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xd9f02683d6c0309f1a09ab73050c82ab20caf6706bfde066d02fbea0765d4abf), "metadata");
    }

    function state_FX_026() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(26);
        s.flicker = true;
        s.kills = 10;
    }

    function test_FX_026() public view {
        RenderStateV1 memory s = state_FX_026();
        assertEq(r.stateHash(s), bytes32(0xeb99c068fe4c3b4b8736cce3dfa39c183cebe0915dc58a71e0e2836e446c0954), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x011fe79ec7081859cb20f9b151a3c14e9e9e35b43f8039c6034255098a8fa72b), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x120fa44fa8ee110d6b06958b4d32e948e5efc624266ed644ae244c2b37e1ab72), "metadata");
    }

    function state_FX_027() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(27);
        s.kills = 75;
        s.deaths = 1;
        s.sealsRemaining = 2;
        s.forcedPurges = 6;
        s.savesReceived = 3;
        s.latestSeasonBadgeFlags = 3;
        s.latestSeasonRank = 1;
        s.latestAwardSeasonId = 1;
        s.territoryAchievementCount = 4;
        s.currentKillStreak = 5;
    }

    function test_FX_027() public view {
        RenderStateV1 memory s = state_FX_027();
        assertEq(r.stateHash(s), bytes32(0x94a38a1be0c640af2ba0fb7f13c73975919a27de606875dc2a9c98d32320291a), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xcf0c1fb6538f12a51e29072a4f3b6dd9b5211fda095af0d510423dcc27f33000), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xf7afc22940c5ea97159bfd4b4eb6c505ae0c3f313d6f407582802cf2961cc6cb), "metadata");
    }

    function state_FX_028() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(28);
        s.sealsRemaining = 0;
    }

    function test_FX_028() public view {
        RenderStateV1 memory s = state_FX_028();
        assertEq(r.stateHash(s), bytes32(0xda4ef24e43b1f47d1fb4b57c1287b70cb30e0f8f309da25150d2f16d6b76dcc1), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x4e1020874634d4fed2929e675fd961f3d5bd539a72eb3a815692886bf4924940), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x78593def040fec7d811019c580a048d135773dee14a24718d33c6e40541ebe20), "metadata");
        assertEq(keccak256(bytes(r.renderBanner(s))), bytes32(0x16f973f6682d71afa753344d1f431db29084b683a380fc6d257ddd53ae1a563c), "banner");
    }

    function state_FX_029() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(29);
        s.witsecApplies = true;
        s.laidLow = true;
        s.exposureState = 3;
    }

    function test_FX_029() public view {
        RenderStateV1 memory s = state_FX_029();
        assertEq(r.stateHash(s), bytes32(0x14b859a6643a70d1ccebd3457bdb30e11c8f5ca24897d556a2cd13ae38cf513a), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0x0e7099cccfbf66e0bc8bb4bac0ab1d5918ba5fe9ae316a91d6757b62cb57fa50), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0x1e24bf0c5a03ad897df1236b00f4ab05f89bc33c836029a5e0cda3ede04fd243), "metadata");
    }

    function state_FX_030() internal pure returns (RenderStateV1 memory s) {
        s = defaultState(30);
        s.lifeState = 3;
        s.exposureState = 6;
        s.deaths = 3;
        s.sealsRemaining = 0;
        s.marked = true;
    }

    function test_FX_030() public view {
        RenderStateV1 memory s = state_FX_030();
        assertEq(r.stateHash(s), bytes32(0x8dd94935c083ceff847ef5697cb033c237695edce16f75e4ab22c1dee478d082), "stateHash");
        assertEq(keccak256(bytes(r.renderSVG(s))), bytes32(0xb0755756cfb191df7c843f35773a73df980291665da10ef60ec26f1f1bf6db38), "svg");
        assertEq(keccak256(bytes(r.renderMetadata(s))), bytes32(0xb1fd19cb85233fa22feeba2febfe134a14b6af460f3cbb516dbcdf3bb6b3f8dd), "metadata");
    }

}
